config/routes.rb
Rails.application.routes.draw do

  devise_for :oranges, controllers: { sessions: "oranges/sessions" }
  devise_for :students, controllers: { sessions: "students/sessions" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#home'
  
  resources 'forms'
  get 'institutions/:id' => 'institutions#show', :as => :institution
  get 'home' => 'static_pages#home'

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: [:show, :edit, :update, :destroy]

  # GET /forms
  # GET /forms.json
  def index
    if orange_signed_in?
      @title = 'Moksleivių'
      @forms = Form.all
    elsif student_signed_in?
      @title = 'Tavo'
      @forms = current_student.forms
    else
      redirect_to root_url, alert: 'Negalite peržiūrėti šių anketų!'
    end
  end

  # GET /forms/1
  # GET /forms/1.json
  def show
    if !(student_authorized? or orange_signed_in?)
      redirect_to root_url, alert: 'Negalite peržiūrėti šios anketos!'
    end
  end

  # GET /forms/new
  def new
    if !student_signed_in?
      redirect_to root_url, alert: 'Anketas gali kurti tik moksleiviai!'
      return
    end
    @form = Form.new
    if params[:institution_id].present?
      @form.institution_id = params[:institution_id]
      @institution = Institution.find(@form.institution_id)
    end
  end

  # GET /forms/1/edit
  def edit
    if !student_authorized?
      redirect_to root_url, alert: 'Negalite redaguoti šios anketos!'
    end
  end

  # POST /forms
  # POST /forms.json
  def create
    if !student_signed_in?
      format.html { redirect_to root_url, notice: 'Anketas gali kurti tik moksleiviai!' }
      format.json { render json: 'Anketas gali kurti tik moksleiviai!', status: :unauthorized }
      return
    end

    @form = Form.new(form_params)
    @form.student_id = current_student.id

    respond_to do |format|
      if @form.save
        format.html { redirect_to @form, notice: 'Anketa buvo sėkmingai sukurta.' }
        format.json { render :show, status: :created, location: @form }
      else
        format.html { render :new }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1
  # PATCH/PUT /forms/1.json
  def update
    if !student_authorized?
      redirect_to root_url, alert: 'Negalite redaguoti šios anketos!'
    end

    respond_to do |format|
      if @form.update(form_params)
        format.html { redirect_to @form, notice: 'Form was successfully updated.' }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    if !student_authorized?
      format.html { redirect_to root_url, alert: 'Negalite ištrinti šios anketos!' }
      format.json { render json: 'Negalite ištrinti šios anketos!', status: :unauthorized }
    end

    @form.destroy
    respond_to do |format|
      format.html { redirect_to forms_url, notice: 'Form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_params
      params[:form].permit(:title, :info)
    end

    def student_authorized?
      (student_signed_in? and @form.student == current_student)
    end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<%= form_for(@form) do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
      <% @form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, "Pavadinimas" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div>
    <%= f.label :info, "Papildoma informacija" %>
    <%= f.text_area :info, class: "form-control" %>
  </div>


  <% if @form.institution.present? %>
    <div>
      <%= f.label :institution, "Pasirinkta institucija" %>
      <p><%= @form.institution.title %></p>
    </div>
  <% end %>

  <br/>

  <div class="actions">
    <%= f.submit "Patvirtinti", class: "btn btn-large btn-primary"  %>
  </div>
<% end %>

app/views/forms/edit.html.erb
<h1>Anketos redagavimas</h1>

<%= render 'form' %>

<%= link_to 'Show', @form %> |
<%= link_to 'Back', forms_path %>

app/views/forms/index.html.erb
<% if @forms.any? %>
  <h2><%= @title %> anketos:</h2>
  <%= render 'shared/forms' %>
<% else %>
  <h2><%= @title %> anketų nėra.</h2>
<% end %>

<br>

<% if student_signed_in? %>
  <%= link_to 'New Form', new_form_path %>
<% end %>

app/views/forms/new.html.erb
<h1>Nauja Anketa</h1>

<%= render 'form' %>

<%= link_to 'Back', forms_path %>

app/views/forms/show.html.erb
<div>
  <h4>Pavadinimas</h4>
  <p><%= @form.title %><p>
</div>

<div>
  <h4>Papildoma informacija</h4>
  <p><%= @form.info %></p>
</div>


<% if @form.institution.present? %>
  <div>
    <h4>Pasirinkta institucija</h4>
    <p><%= @form.institution.title %></p>
  </div>
<% end %>

<%= link_to 'Edit', edit_form_path(@form) %> |
<%= link_to 'Back', forms_path %>