config/routes.rb
Rails.application.routes.draw do

  devise_for :oranges, controllers: { sessions: "oranges/sessions" }
  devise_for :students, controllers: { sessions: "students/sessions" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#home'
  
  resources 'forms'
  get 'institutions/:id' => 'institutions#show', :as => :institution
  get 'home' => 'static_pages#home'

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "usuo", root_path, id: "logo" %>
    <nav class="collapse navbar-collapse">
      <ul class="nav navbar-nav">

      <% if student_signed_in? %>
        <li class="greeting">Sveikas, Moksleivi!</li>
      <% end %>

      <% if orange_signed_in? %>
        <li class="greeting">Sveikas, Oranžini!</li>
      <% end %>
      
      </ul>
      <ul class="nav navbar-nav navbar-right">

      <% if anyone_signed_in? %>
        <li>
          <%= link_to('Nustatymai', edit_registration_path(current_user)) %>
        </li>
        <li>
          <%= link_to('Atsijungti', destroy_session_path(current_user), :method => :delete) %>
        </li>
      <% end %>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Usuo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>